---
apiVersion: v2

type: application

name: google-tag-manager
description: A Helm Chart for Google Tag Manager

version: "0.1.2"
appVersion: "1.16.0"

keywords:
  - google
  - tag
  - manager
  - tagmanager
  - analytics
  - advertising

home: https://github.com/jobtome-labs/google-tag-manager
icon: https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg

sources:
  - https://github.com/jobtome-labs/google-tag-manager

maintainers:
  - name: Daniel Èšoncu
    email: daniel.toncu@jobtome.com
